"""word_unique_by_lemma

Revision ID: 1c2d89987821
Revises: a1b2c3d4e5f6
Create Date: 2026-09-07 13:54:01.149406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2d89987821'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_lang_word_text'), type_='unique')
        batch_op.create_unique_constraint('uq_lang_word_lemma', ['language_code', 'lemma'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lang_word_lemma', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_lang_word_text'), ['language_code', 'text'])

    # ### end Alembic commands ###
