"""Initial schema

Revision ID: 2706d6a909c3
Revises: 
Create Date: 2026-08-27 08:28:50.127153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2706d6a909c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('default_source_lang', sa.String(length=10), nullable=False),
    sa.Column('default_target_lang', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.Column('input_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_user_id'), ['user_id'], unique=False)

    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('lemma', sa.String(length=255), nullable=True),
    sa.Column('pos', sa.String(length=50), nullable=True),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('context_phrase', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_language_code'), ['language_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_words_text'), ['text'], unique=False)

    op.create_table('user_word_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('repetition_number', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recall_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'word_id', name='uq_user_word')
    )
    with op.batch_alter_table('user_word_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_word_stats_next_review_at'), ['next_review_at'], unique=False)
        batch_op.create_index('ix_user_word_stats_user_due', ['user_id', 'next_review_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_word_stats_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_word_stats_word_id'), ['word_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_word_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_word_stats_word_id'))
        batch_op.drop_index(batch_op.f('ix_user_word_stats_user_id'))
        batch_op.drop_index('ix_user_word_stats_user_due')
        batch_op.drop_index(batch_op.f('ix_user_word_stats_next_review_at'))

    op.drop_table('user_word_stats')
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_text'))
        batch_op.drop_index(batch_op.f('ix_words_language_code'))

    op.drop_table('words')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_user_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
