"""add_job_word_association_lesson_word_tables

Revision ID: beed1c2c710f
Revises: 2706d6a909c3
Create Date: 2026-08-27 23:37:10.621997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beed1c2c710f'
down_revision: Union[str, Sequence[str], None] = '2706d6a909c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('lesson_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'word_id', name='uq_lesson_word')
    )
    with op.batch_alter_table('lesson_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_words_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_words_word_id'), ['word_id'], unique=False)

    op.create_table('word_associations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_word_id', sa.Integer(), nullable=False),
    sa.Column('target_word_id', sa.Integer(), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_word_id'], ['words.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_word_id', 'target_word_id', name='uq_source_target_association')
    )
    with op.batch_alter_table('word_associations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_associations_source_lang'), ['source_lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_associations_source_word_id'), ['source_word_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_associations_target_lang'), ['target_lang'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_associations_target_word_id'), ['target_word_id'], unique=False)

    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_lang_word_text', ['language_code', 'text'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_constraint('uq_lang_word_text', type_='unique')

    with op.batch_alter_table('word_associations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_associations_target_word_id'))
        batch_op.drop_index(batch_op.f('ix_word_associations_target_lang'))
        batch_op.drop_index(batch_op.f('ix_word_associations_source_word_id'))
        batch_op.drop_index(batch_op.f('ix_word_associations_source_lang'))

    op.drop_table('word_associations')
    with op.batch_alter_table('lesson_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_words_word_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_words_lesson_id'))

    op.drop_table('lesson_words')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_lesson_id'))

    op.drop_table('jobs')
    # ### end Alembic commands ###
